### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by asceth**
I changed a fair number of things about the code.  Commands now have the ability to parse and consume any options that the Config didn't already consume.  The Deploy command uses this.  You can also now deploy arbitrary branches to environments and specifying an environment is done through options:

``` bash
bundle exec ors deploy to staging
```

as an example.  I'll be testing this more in depth tomorrow on some live existing code bases but thought I'd open up a pull request for some reviewing as well.

### CODE REVIEW

**Comment by jasondew** [comment]
i'm not a fan of the "to" in there, i mean if it's optional that's cool. also you shouldn't need the `bundle exec` in there. Either `bundle install --binstubs` or use the gem, imo, anyway.

**Comment by jasondew** [comment]
it's probably the time to pick a real name for this too.... ideas?

**Comment by asceth** [comment]
bundle exec is habit and not needed.   The to is required to specify an environment other than production (as production is used by default), though you can use from as well so:

``` bash
ors deploy to staging
ors logs from staging
```

It would very easy to also add in -e environment too if that is more appealing (though I favor the from and to)

``` bash
ors deploy -e staging
```

The reason I do it this way is now the environment can be put anywhere in the command as the option parsing takes out the pretending, no gateway and now environment options from the list and whatever is left can be safely consumed by the command.  If we don't have something to signify the environment then we have to force the environment to be last and be required on certain commands such as deploy because otherwise the command and what it does differs.. for example:

``` bash
1) ors deploy origin/feature1 staging
2) ors deploy staging
3) ors deploy origin staging
```

1) says deploy the branch origin/feature1 to staging
2) says deploy the branch staging/production to production  (it parses it as the remote to use when deploying to the default env... production)
3) says deploy the branch origin/production to staging

#### Name

I've been trying to think of something since I started back working on it and haven't come up with anything that really stood out.  A synonym for deploy is supposedly "take battle stations", could call it battle_station or bridge

``` bash
battle_station deploy origin/guided_missile to production
battle_station logs from production
bridge deploy origin/star to hologram
```

Maybe change logs to status for more awesomely worded commands.  :)

**Comment by jasondew** [comment]
Gotcha -- I was hoping for something short though. What about `effect`?

**Comment by asceth** [comment]
That works though is limited to just the left hand typing.  Either way I'll probably alias it to make it even shorter.  

Note:  `effin` uses two hands to type and has the rad tagline "cause sometimes you just want to `effin deploy`"  :)

**Comment by jasondew** [comment]
how about `rudo` like a ruby sudo. you know. "deploy to production". NO. "rudo deploy to production". OK :)

**Comment by asceth** [comment]
+1

**Comment by jasondew** [comment]
awesome. do you want to finish up your round of changes and then i'll make a new repo?

**Comment by asceth** [comment]
Yea I think its close but I'll try and go through it again this weekend and test all the commands.

**Comment by asceth** [comment]
Everything is ready, been using it on some projects now and haven't run into any problems.

**Comment by jasondew** [comment]
merged and bumped the version to 0.3.0

**Pull request merged**
